# Builds ScreenState: the agent executable and the bespoke setup program.
#
#   ./build.ps1                 build everything there is to build
#   ./build.ps1 -SkipInstaller  build only the agent
#
# Outputs:
#   build/bin/ScreenState.exe                the agent
#   dist-installer/ScreenStateSetup.exe      the setup program, carrying the
#                                            agent as an embedded payload
#
# The version is read from VERSION and passed in with -ldflags, so no version
# literal lives anywhere in the source. Note that -X only reaches a var: against
# a const it silently does nothing, which is a whole release shipped announcing
# 0.0.0-dev, so main.version is declared a var on purpose.
param(
    [switch]$SkipInstaller
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

$version = (Get-Content (Join-Path $root 'VERSION')).Trim()
Write-Host "Building ScreenState $version"

# Set before the gate as well as the build, so the tests exercise the same
# configuration that ships.
$env:CGO_ENABLED = '0'

# Verify before building, with no way past it. A gate that can be skipped is a
# gate that is skipped on the day it would have caught something, so there is no
# switch to turn this off: run test.ps1 directly while working; let the build
# insist.
& (Join-Path $root 'test.ps1')
if ($LASTEXITCODE -ne 0) { throw "test.ps1 failed with exit code $LASTEXITCODE" }

# One icon is the whole identity: the agent executable, the setup executable,
# the Start Menu and Desktop shortcuts, the taskbar button and the notification
# area icon all end up wearing it. Each of those reads it out of a binary rather
# than carrying a copy, so placing it on the two executables is the whole job.
#
# The .ico is generated by tools/genicons.py and committed, rather than left for
# a tool to derive from the PNG at build time. It is a failure and no longer a
# warning: the artwork exists, so a build carrying the default icon is a mistake
# rather than a stage of the work.
$icon = Join-Path $root 'assets/application-icon.ico'
$master = Join-Path $root 'assets/application-icon.png'
$manifest = Join-Path $root 'versioninfo.json'
if (-not ((Test-Path $icon) -and (Test-Path $master))) {
    throw 'Missing assets/application-icon.png or .ico: run tools/genicons.py first.'
}
if (-not (Test-Path $manifest)) { throw 'Missing versioninfo.json.' }

# The icon and the version Windows shows in the agent's file properties are
# carried by a resource object the Go toolchain links in when it finds one
# beside the main package. goversioninfo writes it from versioninfo.json.
Write-Host 'Applying the icon and the version resource...'
$syso = Join-Path $root 'resource_windows.syso'
& go run github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest -o $syso -icon $icon -product-version $version -ver-major ($version.Split('.')[0]) -ver-minor ($version.Split('.')[1]) -ver-patch ($version.Split('.')[2]) $manifest
if ($LASTEXITCODE -ne 0) { throw "goversioninfo failed with exit code $LASTEXITCODE" }

# Wails reads the setup program's own icon out of its build directory, so the
# same file is placed there rather than a second one being drawn.
New-Item -ItemType Directory -Force -Path (Join-Path $root 'installer/build/windows') | Out-Null
Copy-Item $master (Join-Path $root 'installer/build/appicon.png') -Force
Copy-Item $icon (Join-Path $root 'installer/build/windows/icon.ico') -Force

Write-Host 'Building the application...'
$binDir = Join-Path $root 'build/bin'
New-Item -ItemType Directory -Force -Path $binDir | Out-Null
$exe = Join-Path $binDir 'ScreenState.exe'

# -H=windowsgui gives the agent no console window, which is what a program that
# lives in the tray wants: started at sign-in it must not flash a black box;
# started from a prompt it must not hold the prompt. It also means the run has no
# error output of its own, which is precisely why the log takes it over.
& go build -trimpath -ldflags "-s -w -H=windowsgui -X main.version=$version" -o $exe .
if ($LASTEXITCODE -ne 0) { throw "go build failed with exit code $LASTEXITCODE" }

# The resource object is a build output rather than source. Leaving it behind
# makes `go build ./...` silently link it into every later build, including ones
# meant to carry a different version.
if (Test-Path $syso) { Remove-Item $syso -Force }

Write-Host "Built $exe"

if ($SkipInstaller) {
    Write-Host "Done: $exe"
    exit 0
}

# The setup program carries the agent inside it, so one downloaded file is the
# whole distribution. The archive is built here rather than committed: a
# multi-megabyte payload in the history would be a copy of an executable that is
# already a build output.
Write-Host 'Packaging the agent as the setup payload...'

# The licence travels with the binary it covers. The setup program says on its
# licence screen that a copy lands in the install folder, so it has to be in the
# payload: a claim on a screen that nothing puts there is a false one.
Copy-Item (Join-Path $root 'LICENSE') (Join-Path $binDir 'LICENSE') -Force

$payload = Join-Path $root 'installer/payload.zip'
if (Test-Path $payload) { Remove-Item $payload -Force }
Compress-Archive -Path (Join-Path $binDir '*') -DestinationPath $payload

# The setup program is a second program in the same module, built as a Wails
# application because it needs a window and the agent does not. The version
# reaches it the same way it reaches the agent, through the linker rather than a
# literal.
Write-Host 'Building the setup program...'
Push-Location (Join-Path $root 'installer')
try {
    wails build -ldflags "-X main.appVersion=$version"
    if ($LASTEXITCODE -ne 0) { throw "wails build failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

Write-Host 'Collecting the setup program...'
$distDir = Join-Path $root 'dist-installer'
New-Item -ItemType Directory -Force -Path $distDir | Out-Null
$setupExe = Join-Path $distDir 'ScreenStateSetup.exe'
Copy-Item (Join-Path $root 'installer/build/bin/ScreenStateSetup.exe') $setupExe -Force

# Put the empty-zip placeholder back, so `go build ./...` and the tests keep
# working without a full build and so a payload never reaches a commit. The
# twenty-two bytes are an end-of-central-directory record with no entries in it,
# which is what an empty archive is.
$empty = [byte[]](0x50, 0x4B, 0x05, 0x06) + (New-Object byte[] 18)
[System.IO.File]::WriteAllBytes($payload, $empty)

Write-Host "Done: $setupExe ($version)"
